const https=require('https');const jwt=require('jsonwebtoken');const fs=require('fs');const T=jwt.sign({id:'t',perfil:'admin'},'italy_secret_2026',{expiresIn:'8h'});const EU='df5f7672-0a6b-402d-ae65-296554236c31';const VEND='b362b262-0b8f-40e3-865f-7eb5bfe226c8';const RIPKE_ID='be617df1-441a-4f11-918e-d813a5ac854c';
const P=(body,mtd)=>new Promise(RR=>{const bdy=mtd!=='DELETE'?JSON.stringify(body):'';const t0=Date.now();const hdr={Accept:'application/json','Cache-Control':'no-cache',Authorization:'Bearer '+T};if(mtd!=='DELETE'){hdr['Content-Type']='application/json';hdr['Content-Length']=Buffer.byteLength(bdy)};const o={host:'adm.italyembalagens.com.br',port:443,method:mtd||'POST',path:mtd==='DELETE'?'/api/ofs/'+body:'/api/ofs',headers:hdr,timeout:240000};const rq=https.request(o,r=>{let b='';r.on('data',d=>b+=d);r.on('end',()=>{try{RR({ms:Date.now()-t0,s:r.statusCode,j:JSON.parse(b),b:b.slice(0,2000)})}catch(e){RR({ms:Date.now()-t0,s:r.statusCode,b})}})});rq.setTimeout(240000,()=>{try{rq.destroy()}catch(_){}RR({ne:'T'})});rq.on('error',e=>RR({ne:String(e?.message||e)}));if(mtd!=='DELETE')rq.write(bdy);rq.end()});
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
const mk=(n,c,p)=>{return{empresa_id:EU,empId:EU,emp_id:'E1',vendedor_id:VEND,vendId:VEND,cli_id:c,cliId:c,cliente_id:c,numero:n,of:n,produto:p,qtd:1,valor_unitario:10,valor_total:10,data_entrega:'2026-12-31',data_pedido:'2026-08-12',status:'Em aberto',caixa_comprimento:10,caixa_largura:10,itens:[{desc:p,qtd:1,valor_unitario:10}],imgs:[]}};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const run=async(name,num,cli,prod,fn)=>{const body=mk(num,cli,prod);const r=await P(body);let id=r.j?.data?.id;const row={t:name,s:r.s,id:(id||'').slice(0,14),cid:(r.j?.data?.cli_id||r.j?.data?.cliente_id||'').slice(0,14),clinome:r.j?.data?.clinome||r.j?.data?.cliente_nome||'',modo:r.j?.data?.modo_resolvido||'',err:r.j?.error||null,ref:r.j?.ref||null,qtd:r.j?.qtd||null,ops:(r.j?.candidatos||[]).map(x=>x.nome).slice(0,5),del:null,ok:false};try{row.ok=!!fn(row)}catch(_){}if(r.s===200&&id){const dd=await P(id,'DELETE');row.del={s:dd.s,ok:!!(dd.s===200||dd.s===204||dd.j?.ok||dd.j?.data?.deleted_at||dd.j?.deleted_at||false}}else{row.del={ok:true,s:null}}console.log(JSON.stringify(row));return row};
(async()=>{const OUT=[];console.log('--- 4 CASOS + prox_num + Baseline + Caso EXATO (MOVEIS RIPKE uppercase igual banco) ---');
  const pn0=await({});try{const u='https://adm.italyembalagens.com.br/api/ofs/proximo-numero?nc='+Date.now();const H={Accept:'application/json','Cache-Control':'no-cache',Authorization:'Bearer '+T};const PROX=await new Promise(RES=>{const RQ=https.request({host:'adm.italyembalagens.com.br',port:443,path:'/api/ofs/proximo-numero?nc='+Date.now(),method:'GET',headers:H,timeout:60000},R=>{let b='';R.on('data',d=>b+=d);R.on('end',()=>{try{RES({j:JSON.parse(b)})}catch(e){RES({b})}})});RQ.setTimeout(60000,()=>{try{RQ.destroy()}catch(_){}RES({ne:'T'})});RQ.on('error',e=>RES({ne:String(e?.message||e)}));RQ.end()});OUT.push({t:'PROX_NUM_ANTES',...PROX.j})}catch(e){}
  OUT.push(await run('BASELINE_UUID','99700',RIPKE_ID,'ZZZ_APAGAR_BASE_UUID_V3',x=>x.s===200&&x.cid.slice(0,8)===RIPKE_ID.slice(0,8)&&norm(x.clinome)===norm('MOVEIS RIPKE')));await wait(600);
  OUT.push(await run('CASO_EXATO_BANCO','99695','MOVEIS RIPKE','ZZZ_APAGAR_EXATO_V3',x=>x.s===200&&x.cid.slice(0,8)===RIPKE_ID.slice(0,8)&&norm(x.clinome)===norm('MOVEIS RIPKE')));await wait(600);
  OUT.push(await run('CASOA_ACENTO_MAIUSC','99699','MÓVEIS RIPKE','ZZZ_APAGAR_CASOA_V3',x=>x.s===200&&x.cid.slice(0,8)===RIPKE_ID.slice(0,8)&&norm(x.clinome)===norm('MOVEIS RIPKE')));await wait(600);
  OUT.push(await run('CASOB_SEMACENTO_MINUSC','99698','moveis ripke','ZZZ_APAGAR_CASOB_V3',x=>x.s===200&&x.cid.slice(0,8)===RIPKE_ID.slice(0,8)&&norm(x.clinome)===norm('MOVEIS RIPKE')));await wait(600);
  OUT.push(await run('CASOC_INEXISTENTE','99697','cliente xablau 9999','ZZZ_APAGAR_CASOC_V3',x=>x.s===400&&String(x.err||'').length>0&&norm(x.ref||'').includes('xablau 9999')));await wait(600);
  OUT.push(await run('CASOD_AMBIGUO','99696','moveis','ZZZ_APAGAR_CASOD_V3',x=>{const amb=x.s===400&&x.qtd!=null&&x.qtd>=2&&x.ops.length>=2;const uniq=x.s===200&&x.cid.length>0;return amb||uniq}));await wait(600);
  try{const H={Accept:'application/json','Cache-Control':'no-cache',Authorization:'Bearer '+T};const PROX=await new Promise(RES=>{const RQ=https.request({host:'adm.italyembalagens.com.br',port:443,path:'/api/ofs/proximo-numero?nc='+Date.now(),method:'GET',headers:H,timeout:60000},R=>{let b='';R.on('data',d=>b+=d);R.on('end',()=>{try{RES({j:JSON.parse(b)})}catch(e){RES({b})}})});RQ.setTimeout(60000,()=>{try{RQ.destroy()}catch(_){}RES({ne:'T'})});RQ.on('error',e=>RES({ne:String(e?.message||e)}));RQ.end()});OUT.push({t:'PROX_NUM_DEPOIS',...PROX.j})}catch(e){}
  const resumo={passou:OUT.filter(x=>x.ok===true).length,total:OUT.filter(x=>typeof x.ok==='boolean').length,tudo:OUT.filter(x=>typeof x.ok==='boolean').every(x=>x.ok===true)};OUT.push({t:'RESUMO',...resumo});
  try{fs.writeFileSync('_SUITE_4_V3.json',JSON.stringify(OUT,null,2))}catch(e){fs.writeFileSync('_SUITE_ERR.txt',String(e.message||e))}
  process.exit(resumo.tudo?0:1);
})().catch(e=>{try{fs.writeFileSync('_SUITE_CATCH3.txt',String(e?.message||e)}catch(_){}console.error('ERRO:',e?.message||e);process.exit(2);});
