const https=require('https');const fs=require('fs');const path=require('path');const jwt=require(path.join(__dirname,'node_modules/jsonwebtoken'));const T=jwt.sign({id:'t',perfil:'admin'},'italy_secret_2026',{expiresIn:'2h'});const p=__dirname;
const P=(u,body,tm)=>new Promise(R=>{const bdy=JSON.stringify(body||{});const t0=Date.now();const hdr={'Content-Type':'application/json','Content-Length':Buffer.byteLength(bdy),Accept:'application/json','Cache-Control':'no-cache',Authorization:'Bearer '+T};const o={host:'adm.italyembalagens.com.br',port:443,path:u,method:'POST',headers:hdr,timeout:tm||60000};const rq=https.request(o,r=>{let b='';r.on('data',d=>b+=d);r.on('end',()=>{let j;try{j=JSON.parse(b)}catch(e){j={pe:e.message,r:b.slice(0,2000)}};R({ms:Date.now()-t0,s:r.statusCode,j,raw:b.slice(0,2500)});});});rq.setTimeout(tm||60000,()=>{try{rq.destroy();}catch(_){}R({ne:'TIMEOUT',tm:Date.now()-t0});});rq.on('error',e=>R({ne:String(e?.message||e)}));rq.write(bdy);rq.end();});
const base={numero:'99990',vendedor_id:'b362b262-0b8f-40e3-865f-7eb5bfe226c8',vendId:'b362b262-0b8f-40e3-865f-7eb5bfe226c8',produto:'ZZZ_TESTE_APAGAR_P3',qtd:1,valor_unitario:10,valor_total:10,data_entrega:'2026-12-31',data_pedido:'2026-08-12',status:'Em aberto',emp_id:'E1',empId:'E1',caixa_comprimento:10,caixa_largura:10,cores_impressao:[],itens:[{desc:'ZZZ_TESTE_APAGAR_P3',qtd:1,valor_unitario:10}],imgs:[]};
(async()=>{const out={feito_em:new Date().toISOString()};
  out.caso1_cliId_nome_texto=await P('/api/ofs',{...base,numero:'99994',cli_id:'MÓVEIS RIPKE',cliId:'MÓVEIS RIPKE',cliente_id:'MÓVEIS RIPKE'},60000);
  out.caso2_cliId_texto_codigo_invalido=await P('/api/ofs',{...base,numero:'99993',cli_id:'codigo_nao_existe_12345',cliId:'codigo_nao_existe_12345',cliente_id:'codigo_nao_existe_12345'},60000);
  out.caso3_cliId_uuid_invalido_formato=await P('/api/ofs',{...base,numero:'99992',cli_id:'cef7e8c5-invalido-formato',cliId:'cef7e8c5-invalido-formato',cliente_id:'cef7e8c5-invalido-formato'},60000);
  out.caso4_cliId_vazio_vendId_ok=await P('/api/ofs',{...base,numero:'99991',cli_id:'',cliId:'',cliente_id:''},60000);
  try{fs.writeFileSync(path.join(p,'_REPRODUCAO_BUG_CLIENTE_INVALIDO.json'),JSON.stringify(out,null,2));}catch(e){try{fs.writeFileSync(path.join(p,'_REPRO_ERR.txt'),String(e?.message||e));}catch(_){}}
  process.exit(0);
})().catch(e=>{try{fs.writeFileSync(path.join(p,'_REPRO_CATCH.txt'),String(e?.message||e));}catch(_){}process.exit(2);});
